[Log]
Level = "debug"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "localhost"
Port = "5433"
MaxConns = 20

[Etherman]
L1URL = "https://geth_goerli.hermez.io"
L2URLs = ["http://core-rpc.hermez-grapefruit.local:8123"]
PrivateKeyPath = "../test/test.keystore"
PrivateKeyPassword = "fA8W3c4RT48g0FPquCnTutiU"

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100
GrpcURL = "core-broadcast.hermez-grapefruit.local:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"